# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://fabricmc.net/develop/
minecraft_version=26.2
loader_version=0.19.3
# Mod Properties
mod_version=1.0
maven_group=de.blazemcworld
archives_base_name=fireflow
# Dependencies
fabric_version=0.154.0+26.2